name: Generate and Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Asciidoctor
        run: |
          sudo apt-get update
          sudo apt-get install asciidoctor

      - name: Generate HTML from AsciiDoc
        run: |
          asciidoctor -D generateddocs ./docs/*.adoc

      - name: Deploy Docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: generateddocs
          destination_dir: projects/doc-test-project
          external_repository: knkg1/kngk1.github.io
          publish_branch: main